---
title: "Building `sunexp` studies"
author: "Florent Chuffart"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true
---


```{r, echo=FALSE, eval=TRUE}
library(epimedtools)
knitr::opts_chunk$set(collapse=TRUE, comment = "#>", fig.width=7, fig.height=7, eval=TRUE, echo=TRUE, results="verbatim")
```


# Building methylom study

```{r}
study_meth_filename = "study_sunexp_meth.rds"
if (!file.exists(study_meth_filename)) {
  study_meth = create_study(study_meth_filename)
  study_meth$gse = "GSE51954"
  foo = study_meth$get_data(dest_dir="~/projects/datashare")
  head(study_meth$data)
  dim(study_meth$data)
  pf_orig = study_meth$platform = suppressWarnings(study_meth$get_platform(dest_dir="~/projects/datashare/platforms"))
  study_meth$platform$CHR = as.character(study_meth$platform$CHR)
  idx = study_meth$platform$CHR != ""
  if (substr(study_meth$platform[idx,]$CHR[1], 1, 3) != "chr") {
    study_meth$platform[idx,]$CHR = paste0("chr", study_meth$platform[idx,]$CHR)    
  }
  study_meth$platform = study_meth$platform[order(study_meth$platform$CHR, study_meth$platform$MAPINFO),]
  study_meth$save(study_meth_filename)
}
if (!exists("study_meth")) {
  study_meth = create_study(study_meth_filename)
}
```


# Building transcriptom study

```{r}
study_sunexp_trscr_filename = "study_sunexp_trscr.rds"
if (!file.exists(study_sunexp_trscr_filename)) {
  study_trscr = create_study(study_sunexp_trscr_filename)
  study_trscr$gse = "GSE67098"
  foo = study_trscr$get_data(dest_dir="~/projects/datashare")
  head(study_trscr$data)
  study_trscr$platform = suppressWarnings(study_trscr$get_platform(dest_dir="~/projects/datashare/platforms"))
  study_trscr$save(study_sunexp_trscr_filename)
}
if (!exists("study_trscr")) {
  study_trscr = create_study(study_sunexp_trscr_filename)
}
```


# Clinical data

```{r}
# sex
study_meth$exp_grp$sex = as.factor(substr(study_meth$exp_grp$characteristics_ch1, 9, 10000))
# histo
study_meth$exp_grp$histo = rep("dermis", nrow(study_meth$exp_grp))
study_meth$exp_grp$histo[grep ("epidermis", study_meth$exp_grp$source_name_ch1)] = "epidermis"
study_meth$exp_grp$histo = as.factor(study_meth$exp_grp$histo)
# age
study_meth$exp_grp$age = substr(study_meth$exp_grp$characteristics_ch1.1, 6, 100)
study_meth$exp_grp$age = as.numeric(study_meth$exp_grp$age)
study_meth$exp_grp$characteristics_ch1.1[is.na(study_meth$exp_grp$age)]
study_meth$exp_grp$age[is.na(study_meth$exp_grp$age)] = 91
study_meth$exp_grp$age_grp = ifelse(study_meth$exp_grp$age < 50, "young", "old")
# sunexp
study_meth$exp_grp$sunexp = substr(study_meth$exp_grp$characteristics_ch1.2, 15, 100)
study_meth$exp_grp$sunexp = as.factor(study_meth$exp_grp$sunexp)
# save
study_meth$save()
```
```{r, results="verbatim"}
table(study_meth$exp_grp$sex, study_meth$exp_grp$histo, study_meth$exp_grp$sunexp, study_meth$exp_grp$age_grp)
```


# CpG Islands 

```{r, eval=FALSE}
cpg_islands_filename = "cpg_islands.rds"
if (!file.exists(cpg_islands_filename)) {
  cpg_islands = sort(unique(as.character(study_meth$platform$UCSC_CpG_Islands_Name)))[-1]
  foo = apply(t(cpg_islands), 2, function(cpg_island) {
    # cpg_island = cpg_islands[1]
    # print(cpg_island)
    s = strsplit(cpg_island, ":")[[1]]
    chrom = s[1]
    len = as.numeric(strsplit(s[2], "-")[[1]])
    # print(s)
    # print(len)
    beg = len[1]
    end = len[2]
    return(list(chrom=chrom, beg=beg, end=end, cpg_island=cpg_island))
  })
  foo = do.call(rbind,foo)
  cpg_islands = data.frame(lapply(data.frame(foo, stringsAsFactors=FALSE), unlist), stringsAsFactors=FALSE)
  cpg_islands$cen = (cpg_islands$end + cpg_islands$beg) / 2 
  cpg_islands$len =  cpg_islands$end - cpg_islands$beg 
  saveRDS(cpg_islands, cpg_islands_filename)
}
cpg_islands = readRDS(cpg_islands_filename)
```





# Session Information

```{r}
sessionInfo()
```

